/**
 * PAGE_LANG - Centralized internationalization dictionary for the Hamro Ghar homepage and main UI.
 * This should eventually be moved to a proper i18n system (e.g., react-i18next).
 */
export const PAGE_LANG = {
    en: {
        heroTag: "No broker spam · Real listings only",
        heroH1a: "Find a home that",
        heroH1b: "feels like you.",
        heroSub: "Search rooms and homes across Nepal in just a few clicks. No hidden fees, no middlemen.",
        searchPlaceholder: "Enter area or city, e.g. Baneshwor, Kathmandu",
        searchBtn: "Search homes",
        heroTrust: "Trusted by members across Nepal",
        heroSignIn: "Already a member? Sign in",
        statsLive: "Live listings",
        statsProps: "properties available right now",
        statsViews: "Average homes viewed per user",
        statsCities: "Cities covered",
        statsQuote: "\u201cClean, simple and fast. Found my flat in 2 days.\u201d",
        strip1Title: "Community platform",
        strip1Text: "Listings are posted by real users — not agencies. Always verify before paying.",
        strip2Title: "Student friendly",
        strip2Text: "Filter by furnished rooms, Wi-Fi, and walking distance.",
        strip3Title: "Human support",
        strip3Text: "Talk to a real person when you feel stuck.",
        riskTitle: "⚠️ Use caution",
        riskText: "HamroGhar does not verify listings. Always visit in person and never pay without seeing the property.",
        filterTypeLabel: "Type:",
        filterForRent: "🏠 Homes for Rent",
        filterWanted: "🔍 Wanted Rooms",
        filterForRentMobile: "For Rent",
        filterWantedMobile: "Wanted",
        filterMap: "🗺️ Show map",
        filterList: "📋 Show list",
        filterApply: "Apply filters",
        filterClear: "Clear",
        filterCityLabel: "City / Area",
        filterCityPlaceholder: "Baneshwor",
        filterMinRent: "Min rent (Rs)",
        filterMaxRent: "Max rent (Rs)",
        filterMinBeds: "Min beds",
        filterPets: "Pets allowed",
        filterFurnished: "Furnished only",
        filterShowing: "Showing",
        filterHomesIn: "homes in",
        filterAllAreas: "All Areas",
        filterBed: "+ bed ",
        listingsLabel: "Featured",
        listingsTitle: "Homes picked for you",
        listingsPage: "Page",
        listingsOf: "of",
        listingsEmpty: "No homes found",
        listingsEmptyHint: "Try adjusting your filters or clearing your search.",
        listingsPrev: "Prev",
        listingsNext: "Next",
        ctaTag: "Membership",
        ctaTitle: "Unlock member-only homes & support",
        ctaSub: "Get saved searches, instant alerts, and priority help from our team — all in one clean dashboard.",
        ctaBtn1: "Get started free",
        ctaBtn2: "View member dashboard",
        communityTitle: "What members say about us",
        communityTag: "Community",
        reviewPlaceholder: "Tell us about your experience finding a home on HamroGhar...",
        reviewSubmit: "Submit review",
        reviewUpdate: "Update",
        reviewRemove: "Remove",
        reviewUpdate2: "Update your review",
        reviewShare: "Share your experience with HamroGhar",
        reviewNone: "No reviews yet. Be the first to share your experience!",
        mapTitle: "Map view",
        mapHint: "Click a district to explore listings in that area.",
    },
    ne: {
        heroTag: "ब्रोकर स्प्याम छैन · वास्तविक लिस्टिङ मात्र",
        heroH1a: "आफ्नो लागि घर खोज्नुस्",
        heroH1b: "ज्युन तपाईंलाई मनपर्छ।",
        heroSub: "नेपालभर कोठा र घर खोज्नुस् — कुनै लुकेको शुल्क वा बिचौलिया छैन।",
        searchPlaceholder: "क्षेत्र वा सहर लेख्नुस्, जस्तै: बानेश्वर, काठमाडौं",
        searchBtn: "घर खोज्नुस्",
        heroTrust: "नेपालभरका सदस्यहरूले भरोसा गर्छन्",
        heroSignIn: "पहिलेदेखि सदस्य हुनुहुन्छ? साइन इन गर्नुस्",
        statsLive: "लाइभ लिस्टिङ",
        statsProps: "अहिले उपलब्ध सम्पत्तिहरू",
        statsViews: "प्रति प्रयोगकर्ता औसत हेरिएका घरहरू",
        statsCities: "शहरहरू समेटिएका",
        statsQuote: "\u201cसरल र छिटो। २ दिनमा फ्ल्याट फेला पाएँ।\u201d",
        strip1Title: "सम्प्रदाय प्लेटफर्म",
        strip1Text: "लिस्टिङहरू एजेन्सीले होइन, वास्तविक प्रयोगकर्ताले पोस्ट गर्छन्। भुक्तानी गर्नु अघि सत्यापन गर्नुस्।",
        strip2Title: "विद्यार्थी अनुकूल",
        strip2Text: "फर्निसड कोठा, Wi-Fi र हिँड्न मिल्ने दूरीका घरहरू फिल्टर गर्नुस्।",
        strip3Title: "मानव सहयोग",
        strip3Text: "अलमलमा परेमा वास्तविक व्यक्तिसँग कुरा गर्नुस्।",
        riskTitle: "⚠️ सावधान रहनुस्",
        riskText: "HamroGhar ले लिस्टिङ प्रमाणित गर्दैन। सधैँ व्यक्तिगत रूपमा भेट्नुस् र सम्पत्ति नदेखी भुक्तानी नगर्नुस्।",
        filterTypeLabel: "प्रकार:",
        filterForRent: "🏠 भाडाको घर",
        filterWanted: "🔍 खोज्दै छु",
        filterForRentMobile: "भाडामा",
        filterWantedMobile: "खोज्दै",
        filterMap: "🗺️ नक्सा देखाउनुस्",
        filterList: "📋 सूची देखाउनुस्",
        filterApply: "फिल्टर लागू गर्नुस्",
        filterClear: "हटाउनुस्",
        filterCityLabel: "सहर / क्षेत्र",
        filterCityPlaceholder: "बानेश्वर",
        filterMinRent: "न्यूनतम भाडा (रु)",
        filterMaxRent: "अधिकतम भाडा (रु)",
        filterMinBeds: "न्यूनतम कोठा",
        filterPets: "पाल्तु जनावर मिल्छ",
        filterFurnished: "फर्निसड मात्र",
        filterShowing: "देखाइँदै छ",
        filterHomesIn: "घरहरू",
        filterAllAreas: "सबै क्षेत्र",
        filterBed: "+ ओछ्यान ",
        listingsLabel: "विशेष",
        listingsTitle: "तपाईंको लागि छानिएका घरहरू",
        listingsPage: "पृष्ठ",
        listingsOf: "मध्ये",
        listingsEmpty: "कुनै घर फेला परेन",
        listingsEmptyHint: "फिल्टर परिवर्तन गर्नुस् वा खोजी हटाउनुस्।",
        listingsPrev: "अघिल्लो",
        listingsNext: "अर्को",
        ctaTag: "सदस्यता",
        ctaTitle: "सदस्य-मात्र घर र सहयोग अनलक गर्नुस्",
        ctaSub: "सेभ गरिएका खोजहरू, तत्काल अलर्ट र प्राथमिक सहयोग पाउनुस्।",
        ctaBtn1: "निःशुल्क सुरु गर्नुस्",
        ctaBtn2: "सदस्य ड्यासबोर्ड हेर्नुस्",
        communityTitle: "सदस्यहरूले हाम्रोबारे के भन्छन्",
        communityTag: "समुदाय",
        reviewPlaceholder: "HamroGhar मा घर खोज्ने अनुभव साझा गर्नुस्...",
        reviewSubmit: "समीक्षा पेश गर्नुस्",
        reviewUpdate: "अपडेट",
        reviewRemove: "हटाउनुस्",
        reviewUpdate2: "आफ्नो समीक्षा अपडेट गर्नुस्",
        reviewShare: "HamroGhar सँगको आफ्नो अनुभव साझा गर्नुस्",
        reviewNone: "अझै समीक्षा छैन। पहिलो हुनुस्!",
        mapTitle: "नक्सा दृश्य",
        mapHint: "जिल्लामा क्लिक गरेर त्यहाँका लिस्टिङहरू हेर्नुस्।",
    },
};

